webtalk_init -webtalk_dir D:/Documents/xsvobo1q/PLD/cv8/PWM_cv8/PWM_cv8.sim/sim_1/behav/xsim/xsim.dir/pwm_driver_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 28 09:50:54 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "175231130_1777487917_210548723_104" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "eba01359-a8f0-4b44-a448-6fd69630e16f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1e123e500b7b47fb9e7aa82704ddeeb7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3300 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40020 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7120_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2663251185 -regid "175231130_1777487917_210548723_104" -xml D:/Documents/xsvobo1q/PLD/cv8/PWM_cv8/PWM_cv8.sim/sim_1/behav/xsim/xsim.dir/pwm_driver_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Documents/xsvobo1q/PLD/cv8/PWM_cv8/PWM_cv8.sim/sim_1/behav/xsim/xsim.dir/pwm_driver_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Documents/xsvobo1q/PLD/cv8/PWM_cv8/PWM_cv8.sim/sim_1/behav/xsim/xsim.dir/pwm_driver_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
