# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_pwm.xci
# IP: The module: 'ila_pwm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_pwm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_pwm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_pwm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_pwm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_pwm.xci
# IP: The module: 'ila_pwm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_pwm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_pwm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_pwm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_pwm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
