# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
set_msg_config  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design vio_v3_0_19_probe_width has unconnected port Bus_rst}}  -suppress 
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Documents/PLD/cv9/cv9_ILA/cv9_ILA.cache/wt [current_project]
set_property parent.project_path D:/Documents/PLD/cv9/cv9_ILA/cv9_ILA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Documents/PLD/cv9/cv9_ILA/cv9_ILA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet D:/Documents/PLD/cv8/PC_08_templates/SOURCES/seg_disp_driver.dcp
set_property used_in_implementation false [get_files D:/Documents/PLD/cv8/PC_08_templates/SOURCES/seg_disp_driver.dcp]
read_vhdl -library xil_defaultlib {
  D:/Documents/PLD/cv8/PC_08_templates/SOURCES/btn_in.vhd
  D:/Documents/PLD/cv8/PC_08_templates/SOURCES/ce_gen.vhd
  D:/Documents/PLD/cv8/PC_08_templates/SOURCES/btn_in/debouncer.vhd
  D:/Documents/PLD/cv8/PC_08_templates/SOURCES/btn_in/edge_detector.vhd
  D:/Documents/PLD/cv8/PC_08_templates/SOURCES/pwm_driver.vhd
  D:/Documents/PLD/cv8/PC_08_templates/SOURCES/btn_in/sync_reg.vhd
  D:/Documents/PLD/cv8/PC_08_templates/SOURCES/rp_top.vhd
}
read_ip -quiet d:/Documents/PLD/cv9/SOURCES/IP/vio_pwm/vio_pwm.xci
set_property used_in_implementation false [get_files -all d:/Documents/PLD/cv9/SOURCES/IP/vio_pwm/vio_pwm.xdc]
set_property used_in_implementation false [get_files -all d:/Documents/PLD/cv9/SOURCES/IP/vio_pwm/vio_pwm_ooc.xdc]

read_ip -quiet d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_pwm.xci
set_property used_in_synthesis false [get_files -all d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Documents/PLD/cv9/SOURCES/IP/ila_pwm/ila_pwm_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Documents/PLD/cv8/PC_08_templates/SOURCES/rp_top.xdc
set_property used_in_implementation false [get_files D:/Documents/PLD/cv8/PC_08_templates/SOURCES/rp_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top rp_top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rp_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rp_top_utilization_synth.rpt -pb rp_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
