# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Documents/xsvobo1q/PLD/cv10/PC_10_template/SOURCES/IP/FIR_50k/FIR_50/FIR_50k/FIR_50k.xci
# IP: The module: 'FIR_50k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/xsvobo1q/PLD/cv10/PC_10_template/SOURCES/IP/FIR_50k/FIR_50/FIR_50k/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_50k'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/xsvobo1q/PLD/cv10/PC_10_template/SOURCES/IP/FIR_50k/FIR_50/FIR_50k/FIR_50k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_50k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Documents/xsvobo1q/PLD/cv10/PC_10_template/SOURCES/IP/FIR_50k/FIR_50/FIR_50k/FIR_50k.xci
# IP: The module: 'FIR_50k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/xsvobo1q/PLD/cv10/PC_10_template/SOURCES/IP/FIR_50k/FIR_50/FIR_50k/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_50k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Documents/xsvobo1q/PLD/cv10/PC_10_template/SOURCES/IP/FIR_50k/FIR_50/FIR_50k/FIR_50k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_50k'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
